// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: ['dist/*'],
    rules: {
      // React Native Reanimated shared values are intentionally mutable, and
      // async refresh effects update state after network I/O.
      'react-hooks/immutability': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    files: ['src/api/**'],
    rules: {
      'import/first': 'off',
    },
  },
  {
    // Generated by `bun run i18n:compile` from the .po catalogs. Reviewing the
    // output is reviewing the wrong artifact -- the .po files are the source,
    // and they are checked in beside these.
    ignores: ['src/i18n/locales/**'],
  },
  {
    // The only file-level exemption in this config, and the only one earned.
    //
    // Everywhere else a render-time ref goes through the documented helpers in
    // src/hooks/use-render-refs.ts, or through a one-line disable naming its
    // reason. This file is different in kind: reading a ref during render is not
    // an implementation detail of what it does, it is what it does. `frozen` is
    // a fact about the outside world at the instant the render runs -- is a
    // finger on the glass -- and reading it any later is the exact lag the hook
    // exists to remove. The argument is written out in the file's own doc
    // comments; per-line disables would only repeat it six times.
    //
    // Still open (card #611): `useFrozenValue` could take its reset detection
    // from `useResetSignal` and shrink what this exemption has to cover. Left
    // alone here because the freeze is being reworked by the streaming-swipe
    // effort and this branch should not race it.
    files: ['src/hooks/use-frozen-value.ts'],
    rules: {
      'react-hooks/refs': 'off',
    },
  },
]);
