// Generated by scripts/sync-builtin-theme.ts. Do not edit; run the script.

export const BUILTIN_THEME_ID = 'cover-courier';
export const BUILTIN_THEME_VERSION = '1.0.6';

/** The manifest exactly as `unpackTheme` accepted it. */
export const BUILTIN_THEME_MANIFEST: unknown = require('../../assets/themes/cover-courier/theme.json');

/** Asset id to Metro asset module, so every file ships in the binary. */
export const BUILTIN_THEME_ASSET_MODULES: Record<string, number> = {
  'courier-dark': require('../../assets/themes/cover-courier/assets/courier-dark.webp'),
  'courier-light': require('../../assets/themes/cover-courier/assets/courier-light.webp'),
  'icon-attach': require('../../assets/themes/cover-courier/assets/icon-attach.webp'),
  'icon-back': require('../../assets/themes/cover-courier/assets/icon-back.webp'),
  'icon-scan': require('../../assets/themes/cover-courier/assets/icon-scan.webp'),
  'icon-send': require('../../assets/themes/cover-courier/assets/icon-send.webp'),
  'icon-settings': require('../../assets/themes/cover-courier/assets/icon-settings.webp'),
  'paper-dark': require('../../assets/themes/cover-courier/assets/paper-dark.webp'),
  'paper-light': require('../../assets/themes/cover-courier/assets/paper-light.webp'),
  preview: require('../../assets/themes/cover-courier/assets/preview.webp'),
};
