// Generated by fizzyx. Do not edit.

import { request } from "./http-request"
export type { ClientConfig } from "./http-request"
export { configure, setToken, setHeaders } from "./http-request"
import type { GetApiAgentsCatalogResponse, DeleteApiDevicesPushTokenRequest, PostApiDevicesPushTokenRequest, PostApiNotificationsTestRequest, PostApiPairClaimRequest, PostApiPairRequestRequest, PostApiSessionsBySessionIdAgentsByTargetSendRequest, PatchApiSessionsBySessionIdPanesByPaneIdRequest, GetApiSessionsBySessionIdPanesByPaneIdApprovalResponse, PostApiSessionsBySessionIdPanesByPaneIdApprovalResponse, PostApiSessionsBySessionIdPanesByPaneIdApprovalRequest, GetApiSessionsBySessionIdPanesByPaneIdFilesResponse, GetApiSessionsBySessionIdPanesByPaneIdPartsResponse, PostApiSessionsBySessionIdPanesByPaneIdSendKeysRequest, PostApiSessionsBySessionIdPanesByPaneIdSendTextRequest, PostApiSessionsBySessionIdPanesByPaneIdSplitRequest, PostApiSessionsBySessionIdPanesByPaneIdZoomRequest, PostApiSessionsBySessionIdSpawnResponse, PostApiSessionsBySessionIdSpawnRequest, PostApiSessionsBySessionIdTabsRequest, PatchApiSessionsBySessionIdTabsByTabIdRequest, GetApiSessionsBySessionIdTabsByTabIdAssetsResponse, PostApiSessionsBySessionIdTasksResponse, PostApiSessionsBySessionIdTasksRequest, PostApiSessionsBySessionIdWorkspacesRequest, PatchApiSessionsBySessionIdWorkspacesByWorkspaceIdRequest, PostApiUploadsResponse, PostApiUploadsRequest } from "./types"

export interface BaseParams {
  [key: string]: unknown
}

/**
 * Herdr resolves an agent kind to its canonical executable itself, so this is a picker feed rather than a launch table: `available` is a PATH probe for that executable on this host, and false is a hint, not a veto. Not session-scoped, because which binaries are installed is a property of the machine. `command` is remapped by `agent_commands` in the gateway's config.json for a host whose binary is named something else.
 */
export function getApiAgentsCatalog(): Promise<GetApiAgentsCatalogResponse> {
  return request<GetApiAgentsCatalogResponse>("GET", `/api/agents/catalog`)
}
export interface GetApiAssetsByAssetIdContentPathParams extends BaseParams {
  assetId: string
}
/**
 * The path must canonicalize to a regular file inside a workspace root the session currently has, so a symlink out of the root, a traversal, and an unknown id are all a 404. An asset indexed while its root was a live workspace outlives that workspace: when the roots no longer contain it, the entry's stored canonical path is replayed and served only if it canonicalizes back to itself byte-for-byte, so a symlink swapped into the old location is the same 404. A path that was never indexed has no entry to replay. The kind is sniffed again from the bytes on every read; a binary asset answers 415 with its metadata and no body. Assets larger than 10 MiB are refused with 413.
 */
export function getApiAssetsByAssetIdContent(params: GetApiAssetsByAssetIdContentPathParams): Promise<void> {
  return request<void>("GET", `/api/assets/${params.assetId}/content`)
}
/**
 * @param data - Request body
 */
export function deleteApiDevicesPushToken(data: DeleteApiDevicesPushTokenRequest): Promise<unknown> {
  return request<unknown, DeleteApiDevicesPushTokenRequest>("DELETE", `/api/devices/push-token`, { body: data })
}
/**
 * @param data - Request body
 */
export function postApiDevicesPushToken(data: PostApiDevicesPushTokenRequest): Promise<unknown> {
  return request<unknown, PostApiDevicesPushTokenRequest>("POST", `/api/devices/push-token`, { body: data })
}
export interface GetApiKeymapsPathParams extends BaseParams {
  sessionId: string
}
export function getApiKeymaps(params: GetApiKeymapsPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/keymaps`)
}
export function getApiMeta(): Promise<unknown> {
  return request<unknown>("GET", `/api/meta`)
}
/**
 * @param data - Request body
 */
export function postApiNotificationsTest(data: PostApiNotificationsTestRequest): Promise<unknown> {
  return request<unknown, PostApiNotificationsTestRequest>("POST", `/api/notifications/test`, { body: data })
}
/**
 * @param data - Request body
 */
export function postApiPairClaim(data: PostApiPairClaimRequest): Promise<unknown> {
  return request<unknown, PostApiPairClaimRequest>("POST", `/api/pair/claim`, { body: data })
}
/**
 * @param data - Request body
 */
export function postApiPairRequest(data: PostApiPairRequestRequest): Promise<unknown> {
  return request<unknown, PostApiPairRequestRequest>("POST", `/api/pair/request`, { body: data })
}
export function getApiPairings(): Promise<unknown> {
  return request<unknown>("GET", `/api/pairings`)
}
export interface DeleteApiPairingsByDeviceIdPathParams extends BaseParams {
  deviceId: string
}
export function deleteApiPairingsByDeviceId(params: DeleteApiPairingsByDeviceIdPathParams): Promise<unknown> {
  return request<unknown>("DELETE", `/api/pairings/${params.deviceId}`)
}
export function getApiSessions(): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions`)
}
export interface GetApiSessionsBySessionIdAgentEventsPathParams extends BaseParams {
  sessionId: string
}
export interface GetApiSessionsBySessionIdAgentEventsQueryParams extends BaseParams {
  /** Only transitions with a higher seq are returned. Absent means everything still held */
  since?: string
}
/**
 * An in-memory ring of the last 200 status transitions per session, for a client building a digest of what happened while it was away. Every transition is recorded, not only the two that raise a push, so a pane that worked and then went idle is visible even though only one notification was sent. Each event carries seq, pane_id, agent, from, to and unix_ms -- ids and statuses, never terminal output or an agent's own wording. Poll with since=<the highest seq already seen>; the answer's next_since is what to send next time, and missed is true when the ring has already dropped something after that point. Nothing is persisted: a restarted gateway answers with an empty list, because it was not watching.
 * @param query.since - Only transitions with a higher seq are returned. Absent means everything still held
 */
export function getApiSessionsBySessionIdAgentEvents(params: GetApiSessionsBySessionIdAgentEventsPathParams, query?: GetApiSessionsBySessionIdAgentEventsQueryParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/agent-events`, { query })
}
export interface GetApiSessionsBySessionIdAgentsPathParams extends BaseParams {
  sessionId: string
}
export function getApiSessionsBySessionIdAgents(params: GetApiSessionsBySessionIdAgentsPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/agents`)
}
export interface GetApiSessionsBySessionIdAgentsByTargetPathParams extends BaseParams {
  sessionId: string
  target: string
}
export function getApiSessionsBySessionIdAgentsByTarget(params: GetApiSessionsBySessionIdAgentsByTargetPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/agents/${params.target}`)
}
export interface PostApiSessionsBySessionIdAgentsByTargetFocusPathParams extends BaseParams {
  sessionId: string
  target: string
}
export function postApiSessionsBySessionIdAgentsByTargetFocus(params: PostApiSessionsBySessionIdAgentsByTargetFocusPathParams): Promise<unknown> {
  return request<unknown>("POST", `/api/sessions/${params.sessionId}/agents/${params.target}/focus`)
}
export interface PostApiSessionsBySessionIdAgentsByTargetSendPathParams extends BaseParams {
  sessionId: string
  target: string
}
/**
 * @param data - Request body
 */
export function postApiSessionsBySessionIdAgentsByTargetSend(params: PostApiSessionsBySessionIdAgentsByTargetSendPathParams, data: PostApiSessionsBySessionIdAgentsByTargetSendRequest): Promise<unknown> {
  return request<unknown, PostApiSessionsBySessionIdAgentsByTargetSendRequest>("POST", `/api/sessions/${params.sessionId}/agents/${params.target}/send`, { body: data })
}
export interface GetApiSessionsBySessionIdEventsPathParams extends BaseParams {
  sessionId: string
}
/**
 * Herdr events arrive as SSE `herdr` events. The gateway adds its own `asset.created` event, carrying one asset in the content-model envelope, when a Herdr worktree event reveals newly produced files. It obeys the same `types=` allow-list, under the name `asset.created`.
 */
export function getApiSessionsBySessionIdEvents(params: GetApiSessionsBySessionIdEventsPathParams): Promise<void> {
  return request<void>("GET", `/api/sessions/${params.sessionId}/events`)
}
export interface GetApiSessionsBySessionIdPanesPathParams extends BaseParams {
  sessionId: string
}
export function getApiSessionsBySessionIdPanes(params: GetApiSessionsBySessionIdPanesPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/panes`)
}
export interface DeleteApiSessionsBySessionIdPanesByPaneIdPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
export function deleteApiSessionsBySessionIdPanesByPaneId(params: DeleteApiSessionsBySessionIdPanesByPaneIdPathParams): Promise<unknown> {
  return request<unknown>("DELETE", `/api/sessions/${params.sessionId}/panes/${params.paneId}`)
}
export interface GetApiSessionsBySessionIdPanesByPaneIdPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
export function getApiSessionsBySessionIdPanesByPaneId(params: GetApiSessionsBySessionIdPanesByPaneIdPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/panes/${params.paneId}`)
}
export interface PatchApiSessionsBySessionIdPanesByPaneIdPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
/**
 * @param data - Request body
 */
export function patchApiSessionsBySessionIdPanesByPaneId(params: PatchApiSessionsBySessionIdPanesByPaneIdPathParams, data: PatchApiSessionsBySessionIdPanesByPaneIdRequest): Promise<unknown> {
  return request<unknown, PatchApiSessionsBySessionIdPanesByPaneIdRequest>("PATCH", `/api/sessions/${params.sessionId}/panes/${params.paneId}`, { body: data })
}
export interface GetApiSessionsBySessionIdPanesByPaneIdApprovalPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
/**
 * Agents ask for permission by drawing a numbered menu and blocking. This reads that menu off the pane's visible screen: the question, the answers, which one the cursor is on, what each answer means (allow, allow_always, deny), and the lines the agent drew around the request. data.state is pending or idle, and data.approval is null when idle. The fingerprint identifies this question with these answers; send it back on POST and an approval that changed underneath is rejected rather than answered blind. Approvals are not parts: docs/content-model.md keeps the part set closed and gives approvals a part type only in v2, so until then they ride their own endpoint and their own SSE events (approval.pending, approval.resolved).
 */
export function getApiSessionsBySessionIdPanesByPaneIdApproval(params: GetApiSessionsBySessionIdPanesByPaneIdApprovalPathParams): Promise<GetApiSessionsBySessionIdPanesByPaneIdApprovalResponse> {
  return request<GetApiSessionsBySessionIdPanesByPaneIdApprovalResponse>("GET", `/api/sessions/${params.sessionId}/panes/${params.paneId}/approval`)
}
export interface PostApiSessionsBySessionIdPanesByPaneIdApprovalPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
/**
 * Answer by option number or by decision (allow, allow_always, deny); the gateway turns it into the keystrokes that agent's menu wants, and confirms with Enter only when the same menu is still standing afterwards. 409 when the pane is not waiting, or when the pending approval is not the one the fingerprint names. Raw send-keys remains the fallback for a menu no client understands.
 * @param data - Request body
 */
export function postApiSessionsBySessionIdPanesByPaneIdApproval(params: PostApiSessionsBySessionIdPanesByPaneIdApprovalPathParams, data: PostApiSessionsBySessionIdPanesByPaneIdApprovalRequest): Promise<PostApiSessionsBySessionIdPanesByPaneIdApprovalResponse> {
  return request<PostApiSessionsBySessionIdPanesByPaneIdApprovalResponse, PostApiSessionsBySessionIdPanesByPaneIdApprovalRequest>("POST", `/api/sessions/${params.sessionId}/panes/${params.paneId}/approval`, { body: data })
}
export interface GetApiSessionsBySessionIdPanesByPaneIdFilesPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
export interface GetApiSessionsBySessionIdPanesByPaneIdFilesQueryParams extends BaseParams {
  /** What the user typed after the @; empty or absent lists the shallowest files */
  query?: string
  /** How many matches to return, 1 to 50, default 20 */
  limit?: string
}
/**
 * Answers paths only -- no contents, no sizes, no absolute paths. The only directory searched is the pane's own working directory as Herdr reports it, canonicalized, which is the same fence the asset API is gated on; a pane sitting at the filesystem root or straight in the home directory has no workspace and answers with an empty list rather than an error, so this cannot be used to probe the host. Symlinks are never followed, and dot, dependency and build directories are skipped, so nothing outside the root can be named. The query is a fuzzy subsequence match over the relative path, ranked so that the file name beats the directories above it; an empty query answers with the shallowest files, which is what a picker shows before anything is typed. kind is decided from the name alone because nothing is read -- the asset content endpoint sniffs the bytes again when a file is actually opened.
 * @param query.query - What the user typed after the @; empty or absent lists the shallowest files
 * @param query.limit - How many matches to return, 1 to 50, default 20
 */
export function getApiSessionsBySessionIdPanesByPaneIdFiles(params: GetApiSessionsBySessionIdPanesByPaneIdFilesPathParams, query?: GetApiSessionsBySessionIdPanesByPaneIdFilesQueryParams): Promise<GetApiSessionsBySessionIdPanesByPaneIdFilesResponse> {
  return request<GetApiSessionsBySessionIdPanesByPaneIdFilesResponse>("GET", `/api/sessions/${params.sessionId}/panes/${params.paneId}/files`, { query })
}
export interface PostApiSessionsBySessionIdPanesByPaneIdFocusPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
export function postApiSessionsBySessionIdPanesByPaneIdFocus(params: PostApiSessionsBySessionIdPanesByPaneIdFocusPathParams): Promise<unknown> {
  return request<unknown>("POST", `/api/sessions/${params.sessionId}/panes/${params.paneId}/focus`)
}
export interface PostApiSessionsBySessionIdPanesByPaneIdInterruptPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
/**
 * Sugar over send-keys, and worth an endpoint because the key is not the same on every agent: ctrl+c at a shell, esc in every agent this gateway has a profile for, and whatever agents.json says when it names one. A keystroke and nothing else -- no signal and no kill. The reply names the key that was sent, so a client can say what it did. The same key is on the pane's shortcuts response as `interrupt`.
 */
export function postApiSessionsBySessionIdPanesByPaneIdInterrupt(params: PostApiSessionsBySessionIdPanesByPaneIdInterruptPathParams): Promise<unknown> {
  return request<unknown>("POST", `/api/sessions/${params.sessionId}/panes/${params.paneId}/interrupt`)
}
export interface GetApiSessionsBySessionIdPanesByPaneIdOutputPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
export interface GetApiSessionsBySessionIdPanesByPaneIdOutputQueryParams extends BaseParams {
  /** Pane read source, for example recent-unwrapped, recent, visible, or detection */
  source?: string
  /** Maximum line count */
  lines?: string
  /** First absolute line to read, 0 being the oldest the pane holds. Requires end. */
  start?: string
  /** One past the last absolute line to read. Requires start. A range wins over lines, and is clamped to 5000 lines and to what the pane holds rather than refused. */
  end?: string
  /** Output format: text or ansi */
  format?: string
}
/**
 * @param query.source - Pane read source, for example recent-unwrapped, recent, visible, or detection
 * @param query.lines - Maximum line count
 * @param query.start - First absolute line to read, 0 being the oldest the pane holds. Requires end.
 * @param query.end - One past the last absolute line to read. Requires start. A range wins over lines, and is clamped to 5000 lines and to what the pane holds rather than refused.
 * @param query.format - Output format: text or ansi
 */
export function getApiSessionsBySessionIdPanesByPaneIdOutput(params: GetApiSessionsBySessionIdPanesByPaneIdOutputPathParams, query?: GetApiSessionsBySessionIdPanesByPaneIdOutputQueryParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/panes/${params.paneId}/output`, { query })
}
export interface GetApiSessionsBySessionIdPanesByPaneIdPartsPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
export interface GetApiSessionsBySessionIdPanesByPaneIdPartsQueryParams extends BaseParams {
  /** How many lines of scrollback to normalize, 1 to 5000, default 400 */
  lines?: string
}
/**
 * Unified content model, schema version 1.4.0. Same envelope as the asset endpoints: schema_version, capabilities, and data, with the ordered parts under data.parts. Two sources can answer, and data.pane.parts says which did. native: the agent runs a protocol the gateway was pointed at (opencode's server API today), so a tool's exit code, the patch an edit produced, the checklist a todo write submitted and any pending permission arrive as data; range then spans the adapter's own rendering, which is the parts' fallback_text joined by newlines. dictionary: the pane's recent-unwrapped text read through the marker table of whichever agent Herdr reports -- Claude Code, Qoder, Codex and opencode. text: no table covers this pane, so everything degraded to prose, which is an answer and not an error. Whichever source answered, every part carries fallback_text verbatim, so an unknown type still renders and a source that drifts loses structure and never loses content. data.pane.composer carries the slash commands this agent understands and whether @ file mentions make sense, and is absent entirely for an agent the gateway has no table for. The raw output endpoint is unchanged and remains the fallback path.
 * @param query.lines - How many lines of scrollback to normalize, 1 to 5000, default 400
 */
export function getApiSessionsBySessionIdPanesByPaneIdParts(params: GetApiSessionsBySessionIdPanesByPaneIdPartsPathParams, query?: GetApiSessionsBySessionIdPanesByPaneIdPartsQueryParams): Promise<GetApiSessionsBySessionIdPanesByPaneIdPartsResponse> {
  return request<GetApiSessionsBySessionIdPanesByPaneIdPartsResponse>("GET", `/api/sessions/${params.sessionId}/panes/${params.paneId}/parts`, { query })
}
export interface PostApiSessionsBySessionIdPanesByPaneIdSendKeysPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
/**
 * @param data - Request body
 */
export function postApiSessionsBySessionIdPanesByPaneIdSendKeys(params: PostApiSessionsBySessionIdPanesByPaneIdSendKeysPathParams, data: PostApiSessionsBySessionIdPanesByPaneIdSendKeysRequest): Promise<unknown> {
  return request<unknown, PostApiSessionsBySessionIdPanesByPaneIdSendKeysRequest>("POST", `/api/sessions/${params.sessionId}/panes/${params.paneId}/send-keys`, { body: data })
}
export interface PostApiSessionsBySessionIdPanesByPaneIdSendTextPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
/**
 * @param data - Request body
 */
export function postApiSessionsBySessionIdPanesByPaneIdSendText(params: PostApiSessionsBySessionIdPanesByPaneIdSendTextPathParams, data: PostApiSessionsBySessionIdPanesByPaneIdSendTextRequest): Promise<unknown> {
  return request<unknown, PostApiSessionsBySessionIdPanesByPaneIdSendTextRequest>("POST", `/api/sessions/${params.sessionId}/panes/${params.paneId}/send-text`, { body: data })
}
export interface GetApiSessionsBySessionIdPanesByPaneIdShortcutsPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
export function getApiSessionsBySessionIdPanesByPaneIdShortcuts(params: GetApiSessionsBySessionIdPanesByPaneIdShortcutsPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/panes/${params.paneId}/shortcuts`)
}
export interface PostApiSessionsBySessionIdPanesByPaneIdSplitPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
/**
 * @param data - Request body
 */
export function postApiSessionsBySessionIdPanesByPaneIdSplit(params: PostApiSessionsBySessionIdPanesByPaneIdSplitPathParams, data: PostApiSessionsBySessionIdPanesByPaneIdSplitRequest): Promise<unknown> {
  return request<unknown, PostApiSessionsBySessionIdPanesByPaneIdSplitRequest>("POST", `/api/sessions/${params.sessionId}/panes/${params.paneId}/split`, { body: data })
}
export interface PostApiSessionsBySessionIdPanesByPaneIdZoomPathParams extends BaseParams {
  sessionId: string
  paneId: string
}
/**
 * Compatibility no-op. Released app builds call this when mounting a terminal; observing a pane must not mutate tmux or Herdr layout.
 * @param data - Request body
 */
export function postApiSessionsBySessionIdPanesByPaneIdZoom(params: PostApiSessionsBySessionIdPanesByPaneIdZoomPathParams, data: PostApiSessionsBySessionIdPanesByPaneIdZoomRequest): Promise<unknown> {
  return request<unknown, PostApiSessionsBySessionIdPanesByPaneIdZoomRequest>("POST", `/api/sessions/${params.sessionId}/panes/${params.paneId}/zoom`, { body: data })
}
export interface GetApiSessionsBySessionIdRecentCwdsPathParams extends BaseParams {
  sessionId: string
}
/**
 * A picker for spawn, and deliberately not a directory browser: it answers with the cwds Herdr reports for the panes that exist right now, deduplicated and held to the same rule the asset scan uses, so the filesystem root and a bare home directory are not on it. Each entry carries path, name, the pane and workspace it came from, and git, which says whether the directory is a checkout. Nothing here can be used to walk the host.
 */
export function getApiSessionsBySessionIdRecentCwds(params: GetApiSessionsBySessionIdRecentCwdsPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/recent-cwds`)
}
export interface GetApiSessionsBySessionIdSnapshotPathParams extends BaseParams {
  sessionId: string
}
export function getApiSessionsBySessionIdSnapshot(params: GetApiSessionsBySessionIdSnapshotPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/snapshot`)
}
export interface PostApiSessionsBySessionIdSpawnPathParams extends BaseParams {
  sessionId: string
}
/**
 * The light half of task dispatch: run this agent, here. The agent must be one this gateway offers -- a Herdr kind or a profile in agents.json -- and cwd, when given, must be a directory this session already works in, exactly the fence repo_path is under; anything else is 403. With tab_id the pane is split off whatever that tab has focused, so a second agent lands beside the first; without it the agent gets a tab of its own. GET recent-cwds answers with the directories cwd will accept. The reply names the pane and says whether the agent came up and whether the prompt landed; a 207 means the pane exists and something after it did not, which is not the same as nothing having happened.
 * @param data - Request body
 */
export function postApiSessionsBySessionIdSpawn(params: PostApiSessionsBySessionIdSpawnPathParams, data: PostApiSessionsBySessionIdSpawnRequest): Promise<PostApiSessionsBySessionIdSpawnResponse> {
  return request<PostApiSessionsBySessionIdSpawnResponse, PostApiSessionsBySessionIdSpawnRequest>("POST", `/api/sessions/${params.sessionId}/spawn`, { body: data })
}
export interface GetApiSessionsBySessionIdTabsPathParams extends BaseParams {
  sessionId: string
}
export function getApiSessionsBySessionIdTabs(params: GetApiSessionsBySessionIdTabsPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/tabs`)
}
export interface PostApiSessionsBySessionIdTabsPathParams extends BaseParams {
  sessionId: string
}
/**
 * @param data - Request body
 */
export function postApiSessionsBySessionIdTabs(params: PostApiSessionsBySessionIdTabsPathParams, data: PostApiSessionsBySessionIdTabsRequest): Promise<unknown> {
  return request<unknown, PostApiSessionsBySessionIdTabsRequest>("POST", `/api/sessions/${params.sessionId}/tabs`, { body: data })
}
export interface DeleteApiSessionsBySessionIdTabsByTabIdPathParams extends BaseParams {
  sessionId: string
  tabId: string
}
export function deleteApiSessionsBySessionIdTabsByTabId(params: DeleteApiSessionsBySessionIdTabsByTabIdPathParams): Promise<unknown> {
  return request<unknown>("DELETE", `/api/sessions/${params.sessionId}/tabs/${params.tabId}`)
}
export interface PatchApiSessionsBySessionIdTabsByTabIdPathParams extends BaseParams {
  sessionId: string
  tabId: string
}
/**
 * @param data - Request body
 */
export function patchApiSessionsBySessionIdTabsByTabId(params: PatchApiSessionsBySessionIdTabsByTabIdPathParams, data: PatchApiSessionsBySessionIdTabsByTabIdRequest): Promise<unknown> {
  return request<unknown, PatchApiSessionsBySessionIdTabsByTabIdRequest>("PATCH", `/api/sessions/${params.sessionId}/tabs/${params.tabId}`, { body: data })
}
export interface GetApiSessionsBySessionIdTabsByTabIdAssetsPathParams extends BaseParams {
  sessionId: string
  tabId: string
}
export interface GetApiSessionsBySessionIdTabsByTabIdAssetsQueryParams extends BaseParams {
  /** Unix milliseconds, the same unit as modified_unix_ms; only files modified strictly after this are returned */
  since?: string
  /** How many assets to return, 1 to 200, default 50 */
  limit?: string
  /** Comma-separated allow-list of kinds -- image, markdown, text, pdf, binary -- filtered during the scan, so kind=image&limit=50 answers with the 50 newest images rather than the images among the 50 newest files. Absent or empty means every kind; a value outside the taxonomy matches nothing rather than erroring. The applied list is echoed back as data.kind */
  kind?: string
  /** Resolve one absolute path exactly, for a file path tapped in terminal output. Takes precedence over since and limit. Answers with one asset, or with none when the path does not canonicalize to a file inside this tab's roots -- a fenced-out path is a miss, not an error */
  path?: string
}
/**
 * Unified content model, schema version 1.0.0. The response is the versioned envelope: schema_version, capabilities, and data, with the assets under data.assets. Assets are fed by the Herdr worktree events the gateway subscribes to, and by an mtime scan of the tab's roots, which is what a cold start uses. The scan is shallow, budgeted, and skips dot directories, dependency directories, and build output. Scoped to tabId, not to the whole session or workspace: a tmux-backed session spans every project the developer has a window open on, and a tmux-backed workspace (a whole tmux session, commonly one long-running session with a window per project) spans every one of those projects too, so this answers only for the one tab the caller is looking at. A herdr-backed session's tabId is resolved to the workspace it belongs to instead, because herdr's own tabs sit inside one of its workspaces and that workspace must not narrow further.
 * @param query.since - Unix milliseconds, the same unit as modified_unix_ms; only files modified strictly after this are returned
 * @param query.limit - How many assets to return, 1 to 200, default 50
 * @param query.kind - Comma-separated allow-list of kinds -- image, markdown, text, pdf, binary -- filtered during the scan, so kind=image&limit=50 answers with the 50 newest images rather than the images among the 50 newest files. Absent or empty means every kind; a value outside the taxonomy matches nothing rather than erroring. The applied list is echoed back as data.kind
 * @param query.path - Resolve one absolute path exactly, for a file path tapped in terminal output. Takes precedence over since and limit. Answers with one asset, or with none when the path does not canonicalize to a file inside this tab's roots -- a fenced-out path is a miss, not an error
 */
export function getApiSessionsBySessionIdTabsByTabIdAssets(params: GetApiSessionsBySessionIdTabsByTabIdAssetsPathParams, query?: GetApiSessionsBySessionIdTabsByTabIdAssetsQueryParams): Promise<GetApiSessionsBySessionIdTabsByTabIdAssetsResponse> {
  return request<GetApiSessionsBySessionIdTabsByTabIdAssetsResponse>("GET", `/api/sessions/${params.sessionId}/tabs/${params.tabId}/assets`, { query })
}
export interface PostApiSessionsBySessionIdTabsByTabIdFocusPathParams extends BaseParams {
  sessionId: string
  tabId: string
}
export function postApiSessionsBySessionIdTabsByTabIdFocus(params: PostApiSessionsBySessionIdTabsByTabIdFocusPathParams): Promise<unknown> {
  return request<unknown>("POST", `/api/sessions/${params.sessionId}/tabs/${params.tabId}/focus`)
}
export interface PostApiSessionsBySessionIdTasksPathParams extends BaseParams {
  sessionId: string
}
/**
 * With `branch_name`, the task gets its own git worktree; without it, the task runs in the repo as it stands. `repo_path` must be, or be inside, a workspace this session already has open -- anything else is 403, and a symlink out of one resolves to the outside path and fails there too. `branch_name` is held to letters, digits, dot, underscore, dash and slash, with `..`, a leading dash, and dot-leading segments refused, so it can only ever be a ref and never an argument. The agent is started with Herdr's `agent.start`, which waits for it to become interactive before the prompt is sent. Asking twice for the same branch reuses the existing checkout rather than making a second one.
 * @param data - Request body
 */
export function postApiSessionsBySessionIdTasks(params: PostApiSessionsBySessionIdTasksPathParams, data: PostApiSessionsBySessionIdTasksRequest): Promise<PostApiSessionsBySessionIdTasksResponse> {
  return request<PostApiSessionsBySessionIdTasksResponse, PostApiSessionsBySessionIdTasksRequest>("POST", `/api/sessions/${params.sessionId}/tasks`, { body: data })
}
export interface GetApiSessionsBySessionIdWorkspacesPathParams extends BaseParams {
  sessionId: string
}
export function getApiSessionsBySessionIdWorkspaces(params: GetApiSessionsBySessionIdWorkspacesPathParams): Promise<unknown> {
  return request<unknown>("GET", `/api/sessions/${params.sessionId}/workspaces`)
}
export interface PostApiSessionsBySessionIdWorkspacesPathParams extends BaseParams {
  sessionId: string
}
/**
 * @param data - Request body
 */
export function postApiSessionsBySessionIdWorkspaces(params: PostApiSessionsBySessionIdWorkspacesPathParams, data: PostApiSessionsBySessionIdWorkspacesRequest): Promise<unknown> {
  return request<unknown, PostApiSessionsBySessionIdWorkspacesRequest>("POST", `/api/sessions/${params.sessionId}/workspaces`, { body: data })
}
export interface DeleteApiSessionsBySessionIdWorkspacesByWorkspaceIdPathParams extends BaseParams {
  sessionId: string
  workspaceId: string
}
export function deleteApiSessionsBySessionIdWorkspacesByWorkspaceId(params: DeleteApiSessionsBySessionIdWorkspacesByWorkspaceIdPathParams): Promise<unknown> {
  return request<unknown>("DELETE", `/api/sessions/${params.sessionId}/workspaces/${params.workspaceId}`)
}
export interface PatchApiSessionsBySessionIdWorkspacesByWorkspaceIdPathParams extends BaseParams {
  sessionId: string
  workspaceId: string
}
/**
 * @param data - Request body
 */
export function patchApiSessionsBySessionIdWorkspacesByWorkspaceId(params: PatchApiSessionsBySessionIdWorkspacesByWorkspaceIdPathParams, data: PatchApiSessionsBySessionIdWorkspacesByWorkspaceIdRequest): Promise<unknown> {
  return request<unknown, PatchApiSessionsBySessionIdWorkspacesByWorkspaceIdRequest>("PATCH", `/api/sessions/${params.sessionId}/workspaces/${params.workspaceId}`, { body: data })
}
export interface PostApiSessionsBySessionIdWorkspacesByWorkspaceIdFocusPathParams extends BaseParams {
  sessionId: string
  workspaceId: string
}
export function postApiSessionsBySessionIdWorkspacesByWorkspaceIdFocus(params: PostApiSessionsBySessionIdWorkspacesByWorkspaceIdFocusPathParams): Promise<unknown> {
  return request<unknown>("POST", `/api/sessions/${params.sessionId}/workspaces/${params.workspaceId}/focus`)
}
/**
 * Images only: png, jpeg, gif, webp, and heic. The type is decided by sniffing the content, not by the filename, and everything else, including executables and scripts, is refused. The stored name is generated by the gateway; the returned name is only the sanitised client name. Uploads are deleted after 48 hours.
 * @param data - Request body
 */
export function postApiUploads(data: PostApiUploadsRequest): Promise<PostApiUploadsResponse> {
  return request<PostApiUploadsResponse, PostApiUploadsRequest>("POST", `/api/uploads`, { body: data })
}
export function getHealth(): Promise<unknown> {
  return request<unknown>("GET", `/health`)
}