// Generated by fizzyx. Do not edit.

export interface GetApiAgentsCatalogResponse {
  agents: { available: boolean; command: string; kind: string; path?: string | null; source: string }[]
  default_startup_timeout_ms: number
}
export interface DeleteApiDevicesPushTokenRequest {
  token: string
}
export interface PostApiDevicesPushTokenRequest {
  device_name?: string
  locale?: string
  platform: string
  token: string
}
export interface PostApiNotificationsTestRequest {
  body?: string
  data?: Record<string, unknown>
  title?: string
}
export interface PostApiPairClaimRequest {
  code: string
  request_id: string
}
export interface PostApiPairRequestRequest {
  device_name?: string
  request_id: string
}
export interface PostApiSessionsBySessionIdAgentsByTargetSendRequest {
  text: string
}
export interface PatchApiSessionsBySessionIdPanesByPaneIdRequest {
  label: string
}
export interface GetApiSessionsBySessionIdPanesByPaneIdApprovalResponse {
  capabilities: { assets: boolean; composer: boolean; image_upload: boolean; parts: boolean }
  data: { answered?: { decision?: string; fingerprint?: string; index?: number }; approval: { context?: string[]; fingerprint: string; hint?: string | null; options: { decision: string; index: number; label: string; selected: boolean }[]; prompt: string; range?: { end: number; start: number }; tool?: string | null } | null; pane: { agent?: string | null; approvals: string; pane_id: string }; pane_id: string; resolved?: boolean; sent_keys?: string[]; session_id: string; state: string }
  schema_version: string
}
export interface PostApiSessionsBySessionIdPanesByPaneIdApprovalResponse {
  capabilities: { assets: boolean; composer: boolean; image_upload: boolean; parts: boolean }
  data: { answered?: { decision?: string; fingerprint?: string; index?: number }; approval: { context?: string[]; fingerprint: string; hint?: string | null; options: { decision: string; index: number; label: string; selected: boolean }[]; prompt: string; range?: { end: number; start: number }; tool?: string | null } | null; pane: { agent?: string | null; approvals: string; pane_id: string }; pane_id: string; resolved?: boolean; sent_keys?: string[]; session_id: string; state: string }
  schema_version: string
}

/**
 * Give option or decision; fingerprint is optional optimistic concurrency.
 */
export interface PostApiSessionsBySessionIdPanesByPaneIdApprovalRequest {
  decision?: string
  fingerprint?: string

  /**
   * The option number the agent printed
   */
  option?: number
}
export interface GetApiSessionsBySessionIdPanesByPaneIdFilesResponse {
  capabilities: { assets: boolean; composer: boolean; image_upload: boolean; parts: boolean }
  data: { files: { kind: string; name: string; path: string }[]; limit?: number; pane_id: string; query?: string; root: string | null; session_id: string }
  schema_version: string
}
export interface GetApiSessionsBySessionIdPanesByPaneIdPartsResponse {
  capabilities: { assets: boolean; composer: boolean; image_upload: boolean; parts: boolean }
  data: { lines?: number; pane: { agent?: string | null; composer?: { captured_from?: string; file_mentions: boolean; slash_commands: { args_hint?: string | null; description: string; name: string; source: string }[]; table: string; version: number }; dictionary?: string | null; image_input: string; native?: { protocol?: string | null; session?: string | null; version?: string | null } | null; pane_id: string; parts: string }; pane_id: string; parts: { approval_id?: string; context?: string[]; fallback_text: string; file?: string | null; hunks?: string[]; input?: string; items?: { done: boolean; text: string }[]; markdown?: string; options?: { decision: string; index: number; label: string }[]; prompt?: string; range?: { end: number; start: number }; result?: string[]; spinner?: boolean; status?: string; text?: string; tool?: string; truncated?: boolean; type: string }[]; revision?: number | null; session_id: string; source?: string }
  schema_version: string
}
export interface PostApiSessionsBySessionIdPanesByPaneIdSendKeysRequest {
  keys: string[]
}
export interface PostApiSessionsBySessionIdPanesByPaneIdSendTextRequest {
  text: string
}
export interface PostApiSessionsBySessionIdPanesByPaneIdSplitRequest {
  command?: string[]
  cwd?: string
  direction: string
  env?: Record<string, unknown>
  ratio?: number
}
export interface PostApiSessionsBySessionIdPanesByPaneIdZoomRequest {
  mode?: string
}
export interface PostApiSessionsBySessionIdSpawnResponse {
  agent: string
  agent_started: boolean
  branch?: string | null

  /**
   * Where the agent runs; also the target for the agent endpoints
   */
  pane_id: string
  prompt_submitted: boolean

  /**
   * True when the branch already had a checkout, which is what makes a retry safe
   */
  reused_worktree?: boolean

  /**
   * What happened, in order: worktree, workspace, agent, prompt, and rollback if one was needed. Present on success and on a partial run alike, so a client never has to guess how far a request got.
   */
  steps: { detail?: Record<string, unknown>; error?: { code: string; message: string }; reason?: string; status: string; step: string }[]
  workspace_id: string

  /**
   * Absent when no branch_name was given
   */
  worktree_path?: string | null
}
export interface PostApiSessionsBySessionIdSpawnRequest {

  /**
   * Agent kind from GET /api/agents/catalog, or a profile named in agents.json
   */
  agent: string

  /**
   * Absolute path, inside a workspace this session has open; omit to take Herdr's default
   */
  cwd?: string

  /**
   * Sent once the agent is interactive
   */
  prompt?: string

  /**
   * Split this tab's focused pane instead of opening a new tab
   */
  tab_id?: string
}
export interface PostApiSessionsBySessionIdTabsRequest {
  cwd?: string
  focus?: boolean
  label?: string
  workspace_id?: string
}
export interface PatchApiSessionsBySessionIdTabsByTabIdRequest {
  label: string
}
export interface GetApiSessionsBySessionIdTabsByTabIdAssetsResponse {
  capabilities: { assets: boolean; composer: boolean; image_upload: boolean; parts: boolean }
  data: { assets: { id: string; kind: string; mime: string; modified_unix_ms: number; name: string; origin: { pane_id?: string; root?: string; session_id: string; workspace_id?: string }; path: string; previewable: boolean; size: number }[]; limit?: number; path?: string | null; roots?: string[]; session_id: string; since?: number | null }
  schema_version: string
}
export interface PostApiSessionsBySessionIdTasksResponse {
  agent: string
  agent_started: boolean
  branch?: string | null

  /**
   * Where the agent runs; also the target for the agent endpoints
   */
  pane_id: string
  prompt_submitted: boolean

  /**
   * True when the branch already had a checkout, which is what makes a retry safe
   */
  reused_worktree?: boolean

  /**
   * What happened, in order: worktree, workspace, agent, prompt, and rollback if one was needed. Present on success and on a partial run alike, so a client never has to guess how far a request got.
   */
  steps: { detail?: Record<string, unknown>; error?: { code: string; message: string }; reason?: string; status: string; step: string }[]
  workspace_id: string

  /**
   * Absent when no branch_name was given
   */
  worktree_path?: string | null
}
export interface PostApiSessionsBySessionIdTasksRequest {

  /**
   * Agent kind from GET /api/agents/catalog
   */
  agent: string
  agent_args?: string[]

  /**
   * Branch for a dedicated worktree; omit to work in the repo as it stands
   */
  branch_name?: string

  /**
   * Sent once the agent is interactive
   */
  prompt?: string

  /**
   * Absolute path, inside a workspace this session has open
   */
  repo_path: string

  /**
   * How long to wait for the agent to become interactive, 3001 to 300000, default 30000
   */
  startup_timeout_ms?: number
  workspace_label?: string
}
export interface PostApiSessionsBySessionIdWorkspacesRequest {
  cwd?: string
  focus?: boolean
  label?: string
}
export interface PatchApiSessionsBySessionIdWorkspacesByWorkspaceIdRequest {
  label: string
}
export interface PostApiUploadsResponse {
  mime: string
  name: string
  path: string
  size: number
}
export interface PostApiUploadsRequest {
  file: string
}