import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { createThemeAuthoringPrompt, THEME_SKILL_VERSION } from '../src/theme/authoring';

const directory = fileURLToPath(new URL('../skills/muqun-theme', import.meta.url));
await mkdir(directory, { recursive: true });
await writeFile(
  resolve(directory, 'SKILL.md'),
  [
    '---',
    'name: muqun-theme',
    'description: This skill should be used when the user asks to create a Muqun theme, customize Muqun colors, or make a theme from reference images',
    `version: ${THEME_SKILL_VERSION}`,
    '---',
    '',
    '<!-- Generated by bun scripts/export-theme-skill.ts; edit src/theme/authoring.ts and schema.ts -->',
    '',
    createThemeAuthoringPrompt(),
    '',
  ].join('\n')
);
