import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { createThemeAuthoringPrompt, THEME_SKILL_VERSION } from '../src/theme/authoring';

const directory = fileURLToPath(new URL('../skills/muqun-theme', import.meta.url));
await mkdir(directory, { recursive: true });
await writeFile(
  resolve(directory, 'SKILL.md'),
  [
    '---',
    'name: muqun-theme',
    'description: This skill should be used when the user asks to create a Muqun theme, customize Muqun colors, or make a theme from reference images',
    `version: ${THEME_SKILL_VERSION}`,
    '---',
    '',
    '<!-- Generated by bun scripts/export-theme-skill.ts; edit src/theme/authoring.ts and schema.ts -->',
    '',
    /*
     * `oxfmt` formats fenced code embedded in Markdown, so the schema fence --
     * one minified line that has to stay byte-identical to `themeJsonSchema()`,
     * which `schema.test.ts` asserts -- would otherwise be expanded into some
     * three hundred lines on the next `bun run format`. The Markdown formatter
     * honours Prettier's ignore directive, so mark that single fence rather
     * than exempting the whole file in `.oxfmtrc.json`: the prose, headings and
     * the second fence stay formatted, and only the block that must not move is
     * left alone. It is added here and not in `createThemeAuthoringPrompt` so
     * the prompt the app delivers to an agent carries no formatter directive.
     */
    createThemeAuthoringPrompt().replace('\n```json\n', '\n<!-- prettier-ignore -->\n```json\n'),
    '',
  ].join('\n')
);
