/**
 * Copy the built-in default theme into the app bundle.
 *
 *   bun scripts/sync-builtin-theme.ts
 *
 * The app ships one theme pack in the binary -- `cover-courier`, from the
 * muqun-themes repository -- and wears it whenever the reader has no theme of
 * their own (`ThemeRepository.active`). This script is how that copy stays in
 * step with its source. It packs the theme with the same CLI the themes
 * repository's CI uses, from a checkout at `$MUQUN_THEMES_DIR` or `../themes`,
 * or, with neither present, downloads the published package from the gallery
 * and checks it against the gallery index's SHA-256. Either way the package is
 * read by the app's own `unpackTheme`, so a pack the importer would refuse
 * never reaches the bundle.
 *
 * It writes:
 *   - `assets/themes/<id>/theme.json`, the manifest as the importer parsed it;
 *   - `assets/themes/<id>/assets/*`, exactly the files the manifest names;
 *   - `src/theme/builtin-theme.generated.ts`, the version and the `require`
 *     map that puts each file in Metro's asset registry on both platforms.
 *
 * Running it twice over the same source changes nothing.
 */
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { unpackTheme } from '../src/theme/package';

const THEME_ID = 'cover-courier';
/** `THEME_GALLERY_BASE` in `src/theme/gallery.ts`, restated to keep React Native out of a script. */
const THEME_GALLERY_BASE = 'https://muqun.dev/api/themes/';
const root = fileURLToPath(new URL('../', import.meta.url));
const target = join(root, 'assets', 'themes', THEME_ID);
const generated = join(root, 'src', 'theme', 'builtin-theme.generated.ts');

function themesCheckout(): string | null {
  for (const candidate of [process.env.MUQUN_THEMES_DIR, join(root, '..', 'themes')]) {
    if (candidate && existsSync(join(candidate, 'src', THEME_ID, 'theme.json')))
      return resolve(candidate);
  }
  return null;
}

function packLocally(checkout: string): Uint8Array {
  const out = join(tmpdir(), `muqun-builtin-${process.pid}.muqun-theme`);
  const result = spawnSync('bunx', ['@osuki-dev/muqun-theme@2', 'pack', THEME_ID, '--out', out], {
    cwd: checkout,
    stdio: ['ignore', 'inherit', 'inherit'],
  });
  if (result.status !== 0) throw new Error(`muqun-theme pack failed in ${checkout}`);
  const bytes = new Uint8Array(readFileSync(out));
  rmSync(out, { force: true });
  return bytes;
}

async function download(): Promise<Uint8Array> {
  const index = (await (await fetch(new URL('index.json', THEME_GALLERY_BASE))).json()) as {
    themes: { id: string; package: string; sha256: string }[];
  };
  const entry = index.themes.find((theme) => theme.id === THEME_ID);
  if (!entry) throw new Error(`${THEME_ID} is not in the published gallery`);
  const response = await fetch(new URL(entry.package, THEME_GALLERY_BASE));
  if (!response.ok) throw new Error(`Download failed: ${response.status}`);
  const bytes = new Uint8Array(await response.arrayBuffer());
  const digest = createHash('sha256').update(bytes).digest('hex');
  if (digest !== entry.sha256) throw new Error('Downloaded package does not match the index');
  return bytes;
}

const checkout = themesCheckout();
console.log(checkout ? `packing ${THEME_ID} from ${checkout}` : `downloading ${THEME_ID}`);
const theme = unpackTheme(checkout ? packLocally(checkout) : await download());
if (theme.manifest.id !== THEME_ID) throw new Error(`Package is ${theme.manifest.id}`);

const files = Object.entries(theme.manifest.assets ?? {})
  .map(([id, asset]) => {
    if (!('path' in asset)) throw new Error(`Asset ${id} has no path`);
    return { id, path: asset.path, bytes: theme.assets[id] };
  })
  .sort((a, b) => a.id.localeCompare(b.id));

mkdirSync(join(target, 'assets'), { recursive: true });
const keep = new Set(files.map((file) => file.path.slice('assets/'.length)));
for (const name of readdirSync(join(target, 'assets')))
  if (!keep.has(name)) rmSync(join(target, 'assets', name));
for (const file of files) writeFileSync(join(target, file.path), file.bytes);
writeFileSync(join(target, 'theme.json'), `${JSON.stringify(theme.manifest, null, 2)}\n`);

const requires = files
  .map((file) => `  '${file.id}': require('../../assets/themes/${THEME_ID}/${file.path}'),`)
  .join('\n');
writeFileSync(
  generated,
  `// Generated by scripts/sync-builtin-theme.ts. Do not edit; run the script.

export const BUILTIN_THEME_ID = '${THEME_ID}';
export const BUILTIN_THEME_VERSION = '${theme.manifest.version}';

/** The manifest exactly as \`unpackTheme\` accepted it. */
export const BUILTIN_THEME_MANIFEST: unknown = require('../../assets/themes/${THEME_ID}/theme.json');

/** Asset id to Metro asset module, so every file ships in the binary. */
export const BUILTIN_THEME_ASSET_MODULES: Record<string, number> = {
${requires}
};
`
);

// Hand both outputs to the repository's formatter, so a re-run is byte-stable
// against what `format:check` accepts.
spawnSync(
  join(root, 'node_modules', '.bin', 'oxfmt'),
  ['--write', generated, join(target, 'theme.json')],
  {
    cwd: root,
    stdio: 'inherit',
  }
);

const total = files.reduce((sum, file) => sum + file.bytes.length, 0);
console.log(
  `${THEME_ID} ${theme.manifest.version}: ${files.length} assets, ${(total / 1024 / 1024).toFixed(2)} MiB`
);
